name: Beta Mirroring

on:
  push:
    branches: [ beta ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Pushes to another repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@github.com:Custom-Roles-for-TTT/TTT-Custom-Roles-Beta.git
          ssh_private_key: ${{ secrets.SSH_DEPLOY_KEY }}
